{% set version = "0.34.0" %}

package:
  name: go-tools
  version: {{ version }}

source:
  url: https://github.com/golang/tools/archive/v{{ version }}.tar.gz
  sha256: ed3063f864a4c3e12f02dc4553d087b22b3b5f09f881e977613772e3f2324ab9

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands: |
    go-auth-authtest 2>&1 | grep -q "go-auth-authtest"
    go-auth-cookieauth 2>&1 | grep -q "go-auth-cookieauth"
    go-auth-gitauth 2>&1 | grep -q "go-auth-gitauth"
    go-auth-netrcauth 2>&1 | grep -q "go-auth-netrcauth"
    go-bisect 2>&1 | grep -q "usage: bisect"
    go-bundle --help
    go-callgraph --help
    go-compilebench --help 2>&1 | grep -q "usage: compilebench"
    go-deadcode --help
    go-digraph --help 2>&1 | grep -q "digraph command"
    go-eg --help 2>&1 | grep -q "This tool implements example-based refactoring of expressions."
    go-file2fuzz --help 2>&1 | grep -q "usage: file2fuzz"
    go-fiximports --help
    go-contrib-init --help
    godex --help 2>&1 | grep -q "usage: godex"
    godoc --help 2>&1 | grep -q "usage: godoc"
    goimports --help 2>&1 | grep -q "usage: goimports"
    gomvpkg --help
    gonew --help 2>&1 | grep -q "usage: gonew"
    gotype --help 2>&1 | grep -q "usage: gotype"
    goyacc --help
    go-present --help
    go-present2md --help 2>&1 | grep -q "usage: present2md"
    go-signature-fuzzer-fuzz-driver --help
    go-signature-fuzzer-fuzz-runner --help
    go-splitdwarf  # [unix]
    go-ssadump --help
    go-stress --help
    go-stringer --help
    go-toolstash --help 2>&1 | grep -q "usage: toolstash"
  requires:
    - m2-grep  # [win]

about:
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - license-files/
  summary: Miscellaneous go tools
  home: https://golang.org/x/tools
  dev_url: https://github.com/golang/tools

extra:
  recipe-maintainers:
    - danielnachun
