schema_version: 1

context:
  version: 0.36.0

package:
  name: go-tools
  version: ${{ version }}

source:
  url: https://github.com/golang/tools/archive/v${{ version }}.tar.gz
  sha256: 299d2320e8f6adb5b53fb1a32e613b00cd2263237c2c4f8f3a68885040b2cfb9

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - requirements:
      run:
        - if: win
          then: m2-grep
    script: |
      go-bisect 2>&1 | grep -q "usage: bisect"
      go-bundle --help
      go-callgraph --help
      go-compilebench --help 2>&1 | grep -q "usage: compilebench"
      go-deadcode --help
      go-digraph --help 2>&1 | grep -q "digraph command"
      go-eg --help 2>&1 | grep -q "This tool implements example-based refactoring of expressions."
      go-file2fuzz --help 2>&1 | grep -q "usage: file2fuzz"
      go-fiximports --help
      go-contrib-init --help
      godex --help 2>&1 | grep -q "usage: godex"
      godoc --help 2>&1 | grep -q "usage: godoc"
      goimports --help 2>&1 | grep -q "usage: goimports"
      gomvpkg --help
      gonew --help 2>&1 | grep -q "usage: gonew"
      gotype --help 2>&1 | grep -q "usage: gotype"
      goyacc --help
      go-present --help
      go-present2md --help 2>&1 | grep -q "usage: present2md"
      go-signature-fuzzer-fuzz-driver --help
      go-signature-fuzzer-fuzz-runner --help
      go-ssadump --help
      go-stress --help
      go-stringer --help
      go-toolstash --help 2>&1 | grep -q "usage: toolstash"

about:
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - license-files/
  summary: Miscellaneous go tools
  homepage: https://golang.org/x/tools
  repository: https://github.com/golang/tools

extra:
  recipe-maintainers:
    - danielnachun
